version: '3.4'
services:
  # Cria o banco de dados
  db-postgres:
    image: postgres:10
    container_name: "db-postgres"
    restart: on-failure
    env_file: ./common.env
    ports:
      - 5432:5432
    networks:
      - desafio-sambatech-network
  # Cria a interface do PGAdmin 4
  db-pgadmin:
    image: dpage/pgadmin4
    container_name: "db-pgadmin"
    restart: on-failure
    env_file: ./common.env
    ports:
      - 16543:80
    networks:
      - desafio-sambatech-network
  # Cria o back-end
  back-end:
    image: back-end
    container_name: "back-end"
    restart: on-failure
    env_file: ./common.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db-postgres
    networks:
      - desafio-sambatech-network
networks:
  desafio-sambatech-network:
    driver: bridge